---
dci_topic: OCP-4.4

# -- Components --
# If you don't specify dci_components or dci_components_by_query
# you will get the latest components associated with that topic.
#
# You can specify components via the ID found from dcictl component-list
#dci_components: ['acaf3f29-22bb-4b9f-b5ac-268958a9a67f']
# Or you can query by name or type and tag
#dci_components_by_query: ['name:4.4.5']
#dci_components_by_query: ['type:ocp,tag:ocp-vanilla-4.4-simple-ok']
#If you specify both the components list will be combined.

# By default we don't run the conformance tests
#dci_openshift_agent_conformance: openshift-conformance-minimal

# Specify version of baremetal deploy repo, default is HEAD
#baremetal_deploy_version: HEAD

# By default we do not run cnf tests
# dci_openshift_agent_cnf_tests: all
